services:
  homer:
    image: b4bz/homer:v24.12.1@sha256:4b44a4a9e3294ccef756275271342661c389ae2936e71ac96b911a139de57757
    container_name: dotsec-homer
    ports:
      - "${HOMER_PORT:-9997}:8080"
    volumes:
      - ./config.yml:/www/assets/config.yml:ro
      - ./assets/:/www/assets/icons/:ro
    restart: unless-stopped
    networks:
      - proxy-net
    environment:
      - INIT_ASSETS=1

networks:
  proxy-net:
    name: dotsec-proxy-net
    external: true
